api = "0.4"

[buildpack]
id = "heroku/java-function"
version = "0.3.12"
name = "Java Function"
homepage = "https://github.com/heroku/buildpacks-jvm"
keywords = ["java", "function"]

[[licenses]]
type = "MIT"

[[order]]

[[order.group]]
id = "heroku/jvm"
version = "0.1.6"

[[order.group]]
id = "heroku/maven"
version = "0.2.3"

[[order.group]]
id = "heroku/jvm-function-invoker"
version = "0.2.11"

[metadata]

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/r2f9u0w4/heroku-java-function-buildpack"
