api = "0.8"

[buildpack]
id = "heroku/java-function"
version = "0.3.39"
name = "Java Function"
homepage = "https://github.com/heroku/buildpacks-jvm"
keywords = ["java", "function"]

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[order]]

[[order.group]]
id = "heroku/jvm"
version = "1.0.5"

[[order.group]]
id = "heroku/maven"
version = "1.0.3"

[[order.group]]
id = "heroku/jvm-function-invoker"
version = "0.6.6"

[metadata]

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-java-function-buildpack"
