api = "0.10"

[buildpack]
id = "heroku/java-function"
version = "7.0.8"
name = "Salesforce Java Function"
homepage = "https://github.com/heroku/buildpacks-jvm"
description = "Salesforce's buildpack for Java Functions."

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[order]]

[[order.group]]
id = "heroku/jvm"
version = "7.0.8"

[[order.group]]
id = "heroku/maven"
version = "7.0.8"

[[order.group]]
id = "heroku/jvm-function-invoker"
version = "7.0.8"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-java-function" }
