api = "0.10"

[buildpack]
id = "heroku/gradle"
version = "7.0.7"
name = "Heroku Gradle"
homepage = "https://github.com/heroku/buildpacks-jvm"
description = "Heroku's Gradle buildpack. A component of the 'heroku/java' buildpack."
keywords = ["gradle", "heroku"]
clear-env = true

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-gradle" }
