[env]
CARGO_TARGET_DIR="./target-cargo"

[env.development]
CARGO_PROFILE = "debug"
BUILD_FLAGS = ["build", "--target", "x86_64-unknown-linux-musl", "--features", "vendored-openssl"]

[env.production]
CARGO_PROFILE = "release"
BUILD_FLAGS = ["build", "--target", "x86_64-unknown-linux-musl", "--features", "vendored-openssl", "--release"]

[tasks.build]
args = ["@@split(BUILD_FLAGS, ;)"]

[tasks.build.mac]
dependencies = ["check-crosscompile-mac-deps"]

[tasks.build.mac.env]
"CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER" = "x86_64-linux-musl-ld"
"CC_x86_64_unknown_linux_musl" = "x86_64-linux-musl-gcc"

[tasks.strip]
condition = { profiles = [ "production" ] }
command = "strip"
args = ["target-cargo/x86_64-unknown-linux-musl/${CARGO_PROFILE}/bp_detect", "target-cargo/x86_64-unknown-linux-musl/${CARGO_PROFILE}/bp_build"]

[tasks.check-crosscompile-mac-deps]
script_runner = "@rust"
script = '''
//! ```cargo
//! [dependencies]
//! which = "4.0.2"
//! colored = "2.0.0"
//! ```
// Silence warning from rust-script:
#![allow(non_snake_case)]

use which::which;
use colored::*;
use std::path::PathBuf;
use std::process::exit;

fn main() {
    let required_binaries = vec!["x86_64-linux-musl-ld", "x86_64-linux-musl-gcc"];
    let binaries = required_binaries.iter().map(which).collect::<Result<Vec<PathBuf>, _>>();
    if binaries.is_err() {
        println!("{}", "Required binaries for cross-compilation missing".bold().red());
        println!("{}", "===============================================".bold().red());
        println!("{}", "! Please make sure to install homebrew-musl-cross to enable cross compilation to Linux.".bold().red());
        println!("{}", "! https://github.com/FiloSottile/homebrew-musl-cross".bold().red());
        println!("");
        println!("Exiting...");
        exit(1);
    }
}
'''

[tasks.copy-files]
script_runner = "@rust"
script = '''
//! ```cargo
//! [dependencies]
//! colored = "2.0.0"
//! ```
// Silence warning from rust-script:
#![allow(non_snake_case)]

use colored::*;
use std::path::PathBuf;
use std::fs;
use std::collections::HashMap;

fn main() {
    let destination = PathBuf::from("target");
    if !destination.exists() {
        fs::create_dir_all(&destination.join("bin")).unwrap();
    }

    let mut files = HashMap::new();
    files.insert(PathBuf::from("./target-cargo/x86_64-unknown-linux-musl").join(env!("CARGO_PROFILE")).join("bp_detect"), destination.join("bin/detect"));
    files.insert(PathBuf::from("./target-cargo/x86_64-unknown-linux-musl").join(env!("CARGO_PROFILE")).join("bp_build"), destination.join("bin/build"));
    files.insert(PathBuf::from("./buildpack.toml"), destination.join("buildpack.toml"));
    files.insert(PathBuf::from("./package.toml"), destination.join("package.toml"));

    for (from, to) in &files {
        fs::copy(from, to).unwrap();
    }
}
'''

[tasks.pack]
dependencies = [
   "build",
   "strip",
   "copy-files"
]
