api = "0.4"

[buildpack]
id = "heroku/gradle"
version = "0.0.35"
name = "Gradle"
homepage = "https://github.com/heroku/heroku-buildpack-gradle"
description = "Official Heroku buildpack for Gradle applications."
keywords = ["java", "gradle"]
licenses = ["MIT"]

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]

[metadata.shim]
tarball = "https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/gradle-v35.tgz"
sha256 = "d49db802898e14667ddd98548baf244527875eb6ae4f556c417042540655660c"

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/r2f9u0w4/heroku-gradle-buildpack"
