api = "0.4"

[buildpack]
id = "heroku/scala"
version = "0.0.89"
name = "Scala"
homepage = "https://github.com/heroku/heroku-buildpack-scala"
description = "Official Heroku buildpack for Scala applications. It uses sbt for building."
keywords = ["scala", "sbt"]
licenses = ["MIT"]

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]

[metadata.shim]
tarball = "https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/scala-v89.tgz"
sha256 = "6f595a022ebda2479de30d1d6bbf63d1302fdcea9a88f671a5626de19b3b3829"

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/r2f9u0w4/heroku-scala-buildpack"
