api = "0.4"

[buildpack]
id = "heroku/jvm-function-invoker"
version = "0.2.0"
name = "JVM Function Invoker"
clear-env = true

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]

[metadata.runtime]
url = "https://sf-fx-java-internal-early-access.s3.amazonaws.com/sf-fx-runtime-java-1.0-SNAPSHOT-jar-with-dependencies.jar"
sha256 = "d29275cf21f27b12a0cf4c3b82fbcdfb512a5840792e2acbb0301d25d22d2074"

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/r2f9u0w4/heroku-jvm-function-invoker-buildpack"
