api = "0.10"

[buildpack]
id = "heroku/jvm-function-invoker"
version = "7.0.7"
name = "Salesforce JVM Function Invoker"
homepage = "https://github.com/heroku/buildpacks-jvm"
description = "Salesforce's JVM function invoker buildpack. A component of the 'heroku/java-function' buildpack."
clear-env = true

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[targets]]
os = "linux"
arch = "amd64"

[metadata.runtime]
url = "https://repo1.maven.org/maven2/com/salesforce/functions/sf-fx-runtime-java-runtime/1.1.7/sf-fx-runtime-java-runtime-1.1.7-jar-with-dependencies.jar"
sha256 = "6afdd87639d77c6e033f9c74171baa9c60f3da4fbdbea7a1bef0783f8bb945c6"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-jvm-function-invoker" }
