api = "0.4"

[buildpack]
id = "heroku/jvm-function-invoker"
version = "0.2.10"
name = "JVM Function Invoker"
clear-env = true
homepage = "https://github.com/heroku/buildpacks-jvm"
keywords = ["java", "function"]

[[licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]

[metadata.runtime]
url = "https://repo1.maven.org/maven2/com/salesforce/functions/sf-fx-runtime-java-runtime/0.2.3/sf-fx-runtime-java-runtime-0.2.3-jar-with-dependencies.jar"
sha256 = "d0edf9a1bae4299229f816f028cf5dc5644404a3f39d7f0b8c444262c6786546"

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/r2f9u0w4/heroku-jvm-function-invoker-buildpack"
