api = "0.9"

[buildpack]
id = "heroku/maven"
version = "2.0.0"
name = "Maven"
clear-env = true
homepage = "https://github.com/heroku/buildpacks-jvm"
description = "Official Heroku buildpack for Maven applications."
keywords = ["java", "maven", "mvn"]

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[stacks]]
id = "*"

[metadata]
default-version = "3.6.2"
[metadata.tarballs]
[metadata.tarballs."3.2.5"]
url = "https://lang-jvm.s3.us-east-1.amazonaws.com/maven-3.2.5.tar.gz"
sha256 = "bd37fad4863cd01524f31ada88ce9f0632040976d64561157cafc98959764341"
[metadata.tarballs."3.6.2"]
url = "https://lang-jvm.s3.us-east-1.amazonaws.com/maven-3.6.2.tar.gz"
sha256 = "63fe4e0bf88d5ec732736f4baa2b62172e654130e16c1db02c252c639b9fd3df"
[metadata.tarballs."3.5.4"]
url = "https://lang-jvm.s3.us-east-1.amazonaws.com/maven-3.5.4.tar.gz"
sha256 = "2fa7a911bfef93a3bc0699674efd307a53da28f9179a50b10d183080b1f5bbc0"
[metadata.tarballs."3.3.9"]
url = "https://lang-jvm.s3.us-east-1.amazonaws.com/maven-3.3.9.tar.gz"
sha256 = "72e5a073cd1acb8925a55366a37268d28a5bdde76d4cda4888364068472aa46e"
[metadata.release]
[metadata.release.docker]
repository = "docker.io/heroku/buildpack-maven"
