api = "0.4"

[buildpack]
id = "heroku/maven"
version = "0.2.4"
name = "Maven"
clear-env = true
homepage = "https://github.com/heroku/buildpacks-jvm"
description = "Official Heroku buildpack for Maven applications."
keywords = ["java", "maven", "mvn"]

[[licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/r2f9u0w4/heroku-maven-buildpack"
