[package]
name = "buildpacks-jvm-shared-test"
rust-version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
exponential-backoff = "2"
libcnb-test = "=0.30.2"
ureq = { version = "2", default-features = false, features = ["tls"] }
